//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/MainProject/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""4951a8ef-e63a-4336-a268-2c192f4de3cb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b43d4b10-4459-48c9-a197-cebffb1b470a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""Value"",
                    ""id"": ""b10983e5-efd1-42fc-9aed-80b9e1f136be"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""8284094b-46c1-449d-a22a-3aec12227e0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NetStatsMonitor"",
                    ""type"": ""Button"",
                    ""id"": ""5eb20276-ff1b-4cd7-9464-bc92d627957d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicAttack"",
                    ""type"": ""Button"",
                    ""id"": ""75b6c5be-be12-43a4-adb3-32c8d2031498"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicRanged"",
                    ""type"": ""Button"",
                    ""id"": ""ba9b7d2b-faa4-4140-be4e-574a231abd7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast01"",
                    ""type"": ""Button"",
                    ""id"": ""1690fac8-c145-4039-be34-4c4f2c49aad4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast02"",
                    ""type"": ""Button"",
                    ""id"": ""9de99ed0-c931-4f3d-beef-9d819e9c296f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast03"",
                    ""type"": ""Button"",
                    ""id"": ""6c1ad21c-d22d-435b-9220-c1774d59d7c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast04"",
                    ""type"": ""Button"",
                    ""id"": ""db5d290a-4e98-469a-980d-262d34e8a7f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Button"",
                    ""id"": ""d5d18f5c-2c0e-40bf-a558-6d67a47d68ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d54eb863-388f-49f0-a62b-70b2c6da78c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""13763fde-db8a-4c52-97e1-8106a5db33b8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5f47814d-e780-4b91-9c28-aeb264cf937d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ed52272-0fe7-4227-963d-ab88ea55f16b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9e1f75ae-cb1f-4b91-b0bc-9e5f84c5d1d8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""95f63c27-984e-4c2d-b282-b959d6691977"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1a6ad0b7-8a5d-4987-9167-cfbfd442fb3c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1fa5a78c-0b62-412b-8096-01c8ec1e69fd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50b97e00-eca9-4172-860a-0c9f671013a2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3a5c790-cdce-4307-a8f4-7feb3a0d51fb"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NetStatsMonitor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fdc6e24-5617-4fa4-8bd9-41bf635441f2"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""NetStatsMonitor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d78584df-d269-40a4-a373-fbf9521b3b6b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5b79015-324b-4722-b369-1730649cc081"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1177d0a-34c2-4928-b04a-b7d08f70ec8b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cast01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ca599e2-d764-4740-a63e-29578225fb80"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cast01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33ec9a6f-62c5-41bc-93ba-c3a48d69b679"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cast02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83798efb-5e73-422c-83c4-ed65639f8aea"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cast02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8276f98c-abf7-4e75-8a97-958f9ffa9e62"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cast03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0bc2d29-0d3c-461f-b43a-eb44565fbfc9"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cast03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53ec547a-5bed-4b3c-99b2-87575a9ad005"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cast04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fec85789-1811-4f15-baac-2199fa580c50"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cast04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5b5d85f-9b84-41e1-b796-fe17d190ce10"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""BasicRanged"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0498da9a-1b1d-4795-9fe4-2f9b09c52329"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BasicRanged"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3d063d6-6131-40c2-8d79-891945ea4e21"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ef16e45-9ba9-4583-86c6-6fe173166b4a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8873b674-0669-47d5-9831-287d1a8c6a67"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""fc506695-71c1-4e0b-8db4-f3efdcf80a09"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b8c55495-184a-435b-b2f1-eb0874daa876"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c340770-3fe8-43e6-93d0-0ca9d764e1ae"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""06483ebc-17c9-4a95-aa1a-2d5631ae441f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0fb819bc-1271-4e90-a342-d5e9b0375759"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3ab1d97d-ad18-4eac-8979-61d71fc50ea0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""StartMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc730fe1-726b-42dc-92eb-526d14eab321"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""StartMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraController"",
            ""id"": ""f8dd072b-2b4b-493b-93af-da75f3bd493b"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d00aa22a-196b-471b-b826-29176f656fce"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""Value"",
                    ""id"": ""9a1bbaab-769f-45ac-9c11-a4030b96c8c2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""46296fef-23ad-41c4-8607-dbb248433e6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""ece9cdff-5883-406c-9530-8df2df348ad1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""276a725e-e6c8-47f7-b209-66f80b66574b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""94955057-81a7-44bd-8266-85b272b24df4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""eea40452-393f-4620-95e5-893082d241c5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e867c7a3-ce63-486e-8cc0-9a95ef1953bd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d9d83699-50e5-4fb0-bf73-ad3bbb43ca19"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ba40959-0cec-4cfa-9457-67a3f253c47b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""688b1344-e4a2-442c-8404-190ae26ecece"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3680ef3d-a16c-4451-b934-51df016b8ad6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe3bb5fb-3a1b-4e93-8cd5-dcab629e7779"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dbc6bbd-831d-4596-963c-a831e2dd9fe4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8c31efc9-fffb-45a8-9298-a88f17234132"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b171fabf-7a2c-46db-b77b-9bcf46f4a51b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0a522af5-e275-491b-8ea3-e8bdf37d44a5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a3576d91-b9e0-4018-9b65-8c479fa90c54"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d02345a0-d1ff-4b69-be26-4077c7908a9c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3021dbec-20ed-4bbe-9c80-2ead959d7f22"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""038e09b3-35a5-4854-bb8c-c9bb2e104134"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94a5eb11-7d6f-4236-8188-0f72eb671272"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8a5c904-1c3f-4f6d-824f-ea06c2497c5b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": []
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_Move = m_CharacterControls.FindAction("Move", throwIfNotFound: true);
        m_CharacterControls_RightStick = m_CharacterControls.FindAction("RightStick", throwIfNotFound: true);
        m_CharacterControls_Dash = m_CharacterControls.FindAction("Dash", throwIfNotFound: true);
        m_CharacterControls_NetStatsMonitor = m_CharacterControls.FindAction("NetStatsMonitor", throwIfNotFound: true);
        m_CharacterControls_BasicAttack = m_CharacterControls.FindAction("BasicAttack", throwIfNotFound: true);
        m_CharacterControls_BasicRanged = m_CharacterControls.FindAction("BasicRanged", throwIfNotFound: true);
        m_CharacterControls_Cast01 = m_CharacterControls.FindAction("Cast01", throwIfNotFound: true);
        m_CharacterControls_Cast02 = m_CharacterControls.FindAction("Cast02", throwIfNotFound: true);
        m_CharacterControls_Cast03 = m_CharacterControls.FindAction("Cast03", throwIfNotFound: true);
        m_CharacterControls_Cast04 = m_CharacterControls.FindAction("Cast04", throwIfNotFound: true);
        m_CharacterControls_Heal = m_CharacterControls.FindAction("Heal", throwIfNotFound: true);
        m_CharacterControls_StartMenu = m_CharacterControls.FindAction("StartMenu", throwIfNotFound: true);
        // CameraController
        m_CameraController = asset.FindActionMap("CameraController", throwIfNotFound: true);
        m_CameraController_Move = m_CameraController.FindAction("Move", throwIfNotFound: true);
        m_CameraController_RightStick = m_CameraController.FindAction("RightStick", throwIfNotFound: true);
        m_CameraController_Boost = m_CameraController.FindAction("Boost", throwIfNotFound: true);
        m_CameraController_Up = m_CameraController.FindAction("Up", throwIfNotFound: true);
        m_CameraController_Down = m_CameraController.FindAction("Down", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private ICharacterControlsActions m_CharacterControlsActionsCallbackInterface;
    private readonly InputAction m_CharacterControls_Move;
    private readonly InputAction m_CharacterControls_RightStick;
    private readonly InputAction m_CharacterControls_Dash;
    private readonly InputAction m_CharacterControls_NetStatsMonitor;
    private readonly InputAction m_CharacterControls_BasicAttack;
    private readonly InputAction m_CharacterControls_BasicRanged;
    private readonly InputAction m_CharacterControls_Cast01;
    private readonly InputAction m_CharacterControls_Cast02;
    private readonly InputAction m_CharacterControls_Cast03;
    private readonly InputAction m_CharacterControls_Cast04;
    private readonly InputAction m_CharacterControls_Heal;
    private readonly InputAction m_CharacterControls_StartMenu;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CharacterControls_Move;
        public InputAction @RightStick => m_Wrapper.m_CharacterControls_RightStick;
        public InputAction @Dash => m_Wrapper.m_CharacterControls_Dash;
        public InputAction @NetStatsMonitor => m_Wrapper.m_CharacterControls_NetStatsMonitor;
        public InputAction @BasicAttack => m_Wrapper.m_CharacterControls_BasicAttack;
        public InputAction @BasicRanged => m_Wrapper.m_CharacterControls_BasicRanged;
        public InputAction @Cast01 => m_Wrapper.m_CharacterControls_Cast01;
        public InputAction @Cast02 => m_Wrapper.m_CharacterControls_Cast02;
        public InputAction @Cast03 => m_Wrapper.m_CharacterControls_Cast03;
        public InputAction @Cast04 => m_Wrapper.m_CharacterControls_Cast04;
        public InputAction @Heal => m_Wrapper.m_CharacterControls_Heal;
        public InputAction @StartMenu => m_Wrapper.m_CharacterControls_StartMenu;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @RightStick.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnRightStick;
                @RightStick.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnRightStick;
                @RightStick.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnRightStick;
                @Dash.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @NetStatsMonitor.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnNetStatsMonitor;
                @NetStatsMonitor.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnNetStatsMonitor;
                @NetStatsMonitor.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnNetStatsMonitor;
                @BasicAttack.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicAttack;
                @BasicRanged.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicRanged;
                @BasicRanged.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicRanged;
                @BasicRanged.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnBasicRanged;
                @Cast01.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast01;
                @Cast01.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast01;
                @Cast01.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast01;
                @Cast02.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast02;
                @Cast02.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast02;
                @Cast02.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast02;
                @Cast03.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast03;
                @Cast03.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast03;
                @Cast03.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast03;
                @Cast04.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast04;
                @Cast04.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast04;
                @Cast04.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCast04;
                @Heal.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnHeal;
                @Heal.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnHeal;
                @Heal.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnHeal;
                @StartMenu.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnStartMenu;
                @StartMenu.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnStartMenu;
                @StartMenu.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnStartMenu;
            }
            m_Wrapper.m_CharacterControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @NetStatsMonitor.started += instance.OnNetStatsMonitor;
                @NetStatsMonitor.performed += instance.OnNetStatsMonitor;
                @NetStatsMonitor.canceled += instance.OnNetStatsMonitor;
                @BasicAttack.started += instance.OnBasicAttack;
                @BasicAttack.performed += instance.OnBasicAttack;
                @BasicAttack.canceled += instance.OnBasicAttack;
                @BasicRanged.started += instance.OnBasicRanged;
                @BasicRanged.performed += instance.OnBasicRanged;
                @BasicRanged.canceled += instance.OnBasicRanged;
                @Cast01.started += instance.OnCast01;
                @Cast01.performed += instance.OnCast01;
                @Cast01.canceled += instance.OnCast01;
                @Cast02.started += instance.OnCast02;
                @Cast02.performed += instance.OnCast02;
                @Cast02.canceled += instance.OnCast02;
                @Cast03.started += instance.OnCast03;
                @Cast03.performed += instance.OnCast03;
                @Cast03.canceled += instance.OnCast03;
                @Cast04.started += instance.OnCast04;
                @Cast04.performed += instance.OnCast04;
                @Cast04.canceled += instance.OnCast04;
                @Heal.started += instance.OnHeal;
                @Heal.performed += instance.OnHeal;
                @Heal.canceled += instance.OnHeal;
                @StartMenu.started += instance.OnStartMenu;
                @StartMenu.performed += instance.OnStartMenu;
                @StartMenu.canceled += instance.OnStartMenu;
            }
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);

    // CameraController
    private readonly InputActionMap m_CameraController;
    private ICameraControllerActions m_CameraControllerActionsCallbackInterface;
    private readonly InputAction m_CameraController_Move;
    private readonly InputAction m_CameraController_RightStick;
    private readonly InputAction m_CameraController_Boost;
    private readonly InputAction m_CameraController_Up;
    private readonly InputAction m_CameraController_Down;
    public struct CameraControllerActions
    {
        private @PlayerInput m_Wrapper;
        public CameraControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CameraController_Move;
        public InputAction @RightStick => m_Wrapper.m_CameraController_RightStick;
        public InputAction @Boost => m_Wrapper.m_CameraController_Boost;
        public InputAction @Up => m_Wrapper.m_CameraController_Up;
        public InputAction @Down => m_Wrapper.m_CameraController_Down;
        public InputActionMap Get() { return m_Wrapper.m_CameraController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControllerActions set) { return set.Get(); }
        public void SetCallbacks(ICameraControllerActions instance)
        {
            if (m_Wrapper.m_CameraControllerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnMove;
                @RightStick.started -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnRightStick;
                @RightStick.performed -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnRightStick;
                @RightStick.canceled -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnRightStick;
                @Boost.started -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnBoost;
                @Up.started -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_CameraControllerActionsCallbackInterface.OnDown;
            }
            m_Wrapper.m_CameraControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
            }
        }
    }
    public CameraControllerActions @CameraController => new CameraControllerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface ICharacterControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnNetStatsMonitor(InputAction.CallbackContext context);
        void OnBasicAttack(InputAction.CallbackContext context);
        void OnBasicRanged(InputAction.CallbackContext context);
        void OnCast01(InputAction.CallbackContext context);
        void OnCast02(InputAction.CallbackContext context);
        void OnCast03(InputAction.CallbackContext context);
        void OnCast04(InputAction.CallbackContext context);
        void OnHeal(InputAction.CallbackContext context);
        void OnStartMenu(InputAction.CallbackContext context);
    }
    public interface ICameraControllerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
    }
}
